def to_lower(char):
    #large consonant
    if char == 'Β': return 'β'
    if char == 'Γ': return 'γ'
    if char == 'Δ': return 'δ'
    if char == 'Ζ': return 'ζ'
    if char == 'Θ': return 'θ'
    if char == 'Κ': return 'κ'
    if char == 'Λ': return 'λ'
    if char == 'Μ': return 'μ'
    if char == 'Ν': return 'ν'
    if char == 'Ξ': return 'ξ'
    if char == 'Π': return 'π'
    if char == 'Σ': return 'σ'
    if char == 'Τ': return 'τ'
    if char == 'Φ': return 'φ'
    if char == 'Χ': return 'χ'
    if char == 'Ψ': return 'ψ'
    # large alpha
    if char == 'Α': return 'α'
    if char == 'ᾼ': return 'ᾳ'
    if char == 'Ά': return 'ά'
    if char == 'Ὰ': return 'ὰ'
    if char == 'Ἁ': return 'ἁ'
    if char == 'ᾉ': return 'ᾁ'
    if char == 'Ἅ': return 'ἅ'
    if char == 'ᾍ': return 'ᾅ'
    if char == 'Ἃ': return 'ἃ'
    if char == 'ᾋ': return 'ᾃ'
    if char == 'Ἇ': return 'ἇ'
    if char == 'ᾏ': return 'ᾇ'
    if char == 'Ἀ': return 'ἀ'
    if char == 'ᾈ': return 'ᾀ'
    if char == 'Ἄ': return 'ἄ'
    if char == 'ᾌ': return 'ᾄ'
    if char == 'Ἂ': return 'ἂ'
    if char == 'ᾊ': return 'ᾂ'
    if char == 'Ἆ': return 'ἆ'
    if char == 'ᾎ': return 'ᾆ'
    # large epsilon
    if char == 'Ε': return 'ε'
    if char == 'Έ': return 'έ'
    if char == 'Ὲ': return 'ὲ'
    if char == 'Ἑ': return 'ἑ'
    if char == 'Ἕ': return 'ἕ'
    if char == 'Ἓ': return 'ἓ'
    if char == 'Ἐ': return 'ἐ'
    if char == 'Ἔ': return 'ἔ'
    if char == 'Ἒ': return 'ἒ'
    # large eta
    if char == 'Η': return 'η'
    if char == 'ῌ': return 'ῃ'
    if char == 'Ή': return 'ή'
    if char == 'Ὴ': return 'ῄ'
    if char == 'Ἡ': return 'ὴ'
    if char == 'ᾙ': return 'ῂ'
    if char == 'Ἥ': return 'ἥ'
    if char == 'ᾝ': return 'ᾕ'
    if char == 'Ἣ': return 'ἣ'
    if char == 'ᾛ': return 'ᾓ'
    if char == 'Ἧ': return 'ἧ'
    if char == 'ᾟ': return 'ᾗ'
    if char == 'Ἠ': return 'ἠ'
    if char == 'ᾘ': return 'ᾐ'
    if char == 'Ἤ': return 'ἤ'
    if char == 'ᾜ': return 'ᾔ'
    if char == 'Ἢ': return 'ἢ'
    if char == 'ᾚ': return 'ᾒ'
    if char == 'Ἦ': return 'ἦ'
    if char == 'ᾞ': return 'ᾖ'
    # large iota
    if char == 'Ι': return 'ι'
    if char == 'Ί': return 'ί'
    if char == 'Ὶ': return 'ὶ'
    if char == 'Ἱ': return 'ἱ'
    if char == 'Ἵ': return 'ἵ'
    if char == 'Ἳ': return 'ἳ'
    if char == 'Ἷ': return 'ἷ'
    if char == 'Ἰ': return 'ἰ'
    if char == 'Ἴ': return 'ἴ'
    if char == 'Ἲ': return 'ἲ'
    if char == 'Ἶ': return 'ἶ'
    # large omicron
    if char == 'Ο': return 'ο'
    if char == 'Ό': return 'ό'
    if char == 'Ὸ': return 'ὸ'
    if char == 'Ὁ': return 'ὁ'
    if char == 'Ὅ': return 'ὅ'
    if char == 'Ὃ': return 'ὃ'
    if char == 'Ὀ': return 'ὀ'
    if char == 'Ὄ': return 'ὄ'
    if char == 'Ὂ': return 'ὂ'
    # large rho
    if char == 'Ρ': return 'ρ'
    if char == 'Ῥ': return 'ῥ'
    # large upsilon
    if char == 'Υ': return 'υ'
    if char == 'Ύ': return 'ύ'
    if char == 'Ὺ': return 'ὺ'
    if char == 'Ὑ': return 'ὑ'
    if char == 'Ὕ': return 'ὕ'
    if char == 'Ὓ': return 'ὓ'
    if char == 'Ὗ': return 'ὗ'
    # large omega
    if char == 'Ω': return 'ω'
    if char == 'ῼ': return 'ῳ'
    if char == 'Ώ': return 'ώ'
    if char == 'Ὼ': return 'ὼ'
    if char == 'Ὡ': return 'ὡ'
    if char == 'ᾩ': return 'ᾡ'
    if char == 'Ὥ': return 'ὥ'
    if char == 'ᾭ': return 'ᾥ'
    if char == 'Ὣ': return 'ὣ'
    if char == 'ᾫ': return 'ᾣ'
    if char == 'Ὧ': return 'ὧ'
    if char == 'ᾯ': return 'ᾧ'
    if char == 'Ὠ': return 'ὠ'
    if char == 'ᾨ': return 'ᾠ'
    if char == 'Ὤ': return 'ὤ'
    if char == 'ᾬ': return 'ᾤ'
    if char == 'Ὢ': return 'ὢ'
    if char == 'ᾪ': return 'ᾢ'
    if char == 'Ὦ': return 'ὦ'
    if char == 'ᾮ': return 'ᾦ'
    return char

