def to_upper(char):
    # small consonant
    if char == 'β': return 'Β'
    if char == 'γ': return 'Γ'
    if char == 'δ': return 'Δ'
    if char == 'ζ': return 'Ζ'
    if char == 'θ': return 'Θ'
    if char == 'κ': return 'Κ'
    if char == 'λ': return 'Λ'
    if char == 'μ': return 'Μ'
    if char == 'ν': return 'Ν'
    if char == 'ξ': return 'Ξ'
    if char == 'π': return 'Π'
    if char == 'ς': return 'Σ'
    if char == 'σ': return 'Σ'
    if char == 'τ': return 'Τ'
    if char == 'φ': return 'Φ'
    if char == 'χ': return 'Χ'
    if char == 'ψ': return 'Ψ'
    # small alpha
    if char == 'α': return 'Α'
    if char == 'ᾳ': return 'ᾼ'
    if char == 'ά': return 'Ά'
#   if char == 'ᾴ': return 'ᾴ'
    if char == 'ὰ': return 'Ὰ'
#   if char == 'ᾲ': return 'ᾲ'
#   if char == 'ᾶ': return 'ᾶ'
#   if char == 'ᾷ': return 'ᾷ'
    if char == 'ἁ': return 'Ἁ'
    if char == 'ᾁ': return 'ᾉ'
    if char == 'ἅ': return 'Ἅ'
    if char == 'ᾅ': return 'ᾍ'
    if char == 'ἃ': return 'ᾍ'
    if char == 'ᾃ': return 'ᾍ'
    if char == 'ἇ': return 'Ἇ'
    if char == 'ᾇ': return 'ᾏ'
    if char == 'ἀ': return 'Ἀ'
    if char == 'ᾀ': return 'ᾈ'
    if char == 'ἄ': return 'Ἄ'
    if char == 'ᾄ': return 'ᾌ'
    if char == 'ἂ': return 'Ἂ'
    if char == 'ᾂ': return 'ᾊ'
    if char == 'ἆ': return 'Ἆ'
    if char == 'ᾆ': return 'ᾎ'
    # small epsilon
    if char == 'ε': return 'Ε'
    if char == 'έ': return 'Έ'
    if char == 'ὲ': return 'Ὲ'
    if char == 'ἑ': return 'Ἑ'
    if char == 'ἕ': return 'Ἕ'
    if char == 'ἓ': return 'Ἓ'
    if char == 'ἐ': return 'Ἐ'
    if char == 'ἔ': return 'Ἔ'
    if char == 'ἒ': return 'Ἒ'
    # small eta
    if char == 'η': return 'Η'
    if char == 'ῃ': return 'ῌ'
    if char == 'ή': return 'Ή'
#   if char == 'ῄ': return 'ῄ'
    if char == 'ὴ': return 'Ὴ'
#   if char == 'ῂ': return 'ῂ'
#   if char == 'ῆ': return 'ῆ'
#   if char == 'ῇ': return 'ῇ'
    if char == 'ἡ': return 'Ἡ'
    if char == 'ᾑ': return 'ᾙ'
    if char == 'ἥ': return 'Ἥ'
    if char == 'ᾕ': return 'ᾝ'
    if char == 'ἣ': return 'Ἣ'
    if char == 'ᾓ': return 'ᾛ'
    if char == 'ἧ': return 'Ἧ'
    if char == 'ᾗ': return 'ᾟ'
    if char == 'ἠ': return 'Ἠ'
    if char == 'ᾐ': return 'ᾘ'
    if char == 'ἤ': return 'Ἤ'
    if char == 'ᾔ': return 'ᾜ'
    if char == 'ἢ': return 'Ἢ'
    if char == 'ᾒ': return 'ᾚ'
    if char == 'ἦ': return 'Ἦ'
    if char == 'ᾖ': return 'ᾞ'
    # small iota
    if char == 'ι': return 'Ι'
    if char == 'ί': return 'Ί'
    if char == 'ὶ': return 'Ὶ'
#   if char == 'ῖ': return 'ῖ'
    if char == 'ἱ': return 'Ἱ'
    if char == 'ἵ': return 'Ἵ'
    if char == 'ἳ': return 'Ἳ'
    if char == 'ἷ': return 'Ἷ'
    if char == 'ἰ': return 'Ἰ'
    if char == 'ἴ': return 'Ἴ'
    if char == 'ἲ': return 'Ἲ'
    if char == 'ἶ': return 'Ἶ'
    if char == 'ϊ': return 'Ϊ'
#   if char == 'ΐ': return 'ΐ'
#   if char == 'ῒ': return 'ῒ'
#   if char == 'ῗ': return 'ῗ'
    # small omicron
    if char == 'ο': return 'Ο'
    if char == 'ό': return 'Ό'
    if char == 'ὸ': return 'Ὸ'
    if char == 'ὁ': return 'Ὁ'
    if char == 'ὅ': return 'Ὅ'
    if char == 'ὃ': return 'Ὃ'
    if char == 'ὀ': return 'Ὀ'
    if char == 'ὄ': return 'Ὄ'
    if char == 'ὂ': return 'Ὂ'
    # small rho
    if char == 'ρ': return 'Ρ'
    if char == 'ῥ': return 'Ῥ'
#   if char == 'ῤ': return 'ῤ'
    # small upsilon
    if char == 'υ': return 'Υ'
    if char == 'ύ': return 'Ύ'
    if char == 'ὺ': return 'Ὺ'
#   if char == 'ῦ': return 'ῦ'
    if char == 'ὑ': return 'Ὑ'
    if char == 'ὕ': return 'Ὕ'
    if char == 'ὓ': return 'Ὓ'
    if char == 'ὗ': return 'Ὗ'
#   if char == 'ὐ': return 'ὐ'
#   if char == 'ὔ': return 'ὔ'
#   if char == 'ὒ': return 'ὒ'
#   if char == 'ὖ': return 'ὖ'
    if char == 'ϋ': return 'Ϋ'
#   if char == 'ΰ': return 'ΰ'
#   if char == 'ῢ': return 'ῢ'
#   if char == 'ῧ': return 'ῧ'
    # small omega
    if char == 'ω': return 'Ω'
    if char == 'ῳ': return 'ῼ'
    if char == 'ώ': return 'Ώ'
#   if char == 'ῴ': return 'ῴ'
    if char == 'ὼ': return 'Ὼ'
#   if char == 'ῲ': return 'ῲ'
#   if char == 'ῶ': return 'ῶ'
#   if char == 'ῷ': return 'ῷ'
    if char == 'ὡ': return 'Ὡ'
    if char == 'ᾡ': return 'ᾩ'
    if char == 'ὥ': return 'Ὥ'
    if char == 'ᾥ': return 'ᾭ'
    if char == 'ὣ': return 'Ὣ'
    if char == 'ᾣ': return 'ᾫ'
    if char == 'ὧ': return 'Ὧ'
    if char == 'ᾧ': return 'ᾯ'
    if char == 'ὠ': return 'Ὠ'
    if char == 'ᾠ': return 'ᾨ'
    if char == 'ὤ': return 'Ὤ'
    if char == 'ᾤ': return 'ᾬ'
    if char == 'ὢ': return 'Ὢ'
    if char == 'ᾢ': return 'ᾪ'
    if char == 'ὦ': return 'Ὦ'
    if char == 'ᾦ': return 'ᾮ'
    return char

